### PR TITLE
TomEE module

### PR DESCRIPTION
**Pull request by ggam**
This allows to get the Subject and the ServletRequest from the PolicyContext. Interesingly, the Subject was not available even during EJB invocations.

The obvious limitation is that we don't have the Servlet permissions, but IIRC you already had the code to parse them somewhere? If that's the case, I guess we could do it ourselves and put them on the PolicyConfiguration, allowing near full JACC support for user code?

### CODE REVIEW

**Comment by arjantijms** [comment]
Wow cool PR, thx!

> but IIRC you already had the code to parse them somewhere?

Well, it's not really "me" who had that code, but Geronimo still has ;)

Since Geronimo is obviously license wise compatible with Tomcat, a Tomcat JACC implementation could rather easily take those. We could possibly integrate that code here as well. The parsing rules for servlet constraints haven't changed in ages, to even if Geronimo is old and discontinued effectively, that could would still be usable. The only impediment could be if the code is massively based on the Geronimo GBean components.

**Comment by ggam** [comment]
Could you please point me to the code? I know I've seen it somewhere but
can't find it right now.

I'll try to take a look at it.

**Comment by arjantijms** [comment]
It's a *very* long time ago that I last looked at Geronimo, but one place where the code lives is here:

* https://github.com/apache/geronimo/blob/9836399660856485440d747c74d8c69875c77a89/modules/security/src/java/org/apache/geronimo/security/jacc/ApplicationPolicyConfigurationManager.java

The `org/apache/geronimo/security/jacc` folder contains the default JACC provider, which is not that crazy different from the JACC provider used in this project (if you study a bunch of them, you'll see that they're all pretty similar).

The `ApplicationPolicyConfigurationManager` seems to be the bridge class that puts the pre-processed results of Tomcat's web.xml scanning into the somewhat generic JACC provider.

If I remember correctly, this was the class that took the raw Tomcat result of the web.xml (and annotation) indexing and pre-processed that into the JACC structure that the `ApplicationPolicyConfigurationManager` uses:

https://github.com/apache/geronimo/blob/9836399660856485440d747c74d8c69875c77a89/modules/tomcat-builder/src/java/org/apache/geronimo/tomcat/deployment/TomcatModuleBuilder.java#L533

**Comment by arjantijms** [comment]
p.s. the most interesting lines of code are probably these:

https://github.com/apache/geronimo/blob/9836399660856485440d747c74d8c69875c77a89/modules/tomcat-builder/src/java/org/apache/geronimo/tomcat/deployment/TomcatModuleBuilder.java#L624

**Comment by ggam** [comment]
Thanks for the insight! Looks like the latest revision (trunk branch) has changed a bit (https://github.com/apache/geronimo/blob/trunk/plugins/tomcat/geronimo-tomcat7-builder/src/main/java/org/apache/geronimo/tomcat/deployment/TomcatModuleBuilder.java) but I imagine the idea will still be the same.

Anyway, if we are just going to replicate the web.xml+annotation parsing, couldn't we just reuse OmniFaces WebXml class and base the permission part on another more active project? Or does Geronimo have some specific code we can benefit from?

**Comment by arjantijms** [comment]
Hi,

Probably would be best to base it on the actual Tomcat parsed web.xml
first. OmniFaces is not fully complete at this point.

Although Geronimo is not active, we can copy the code (with keeping the
copyright header, of course and attributing them in a notice file), and
then maintain it from there.

If it’s good enough we may even consider contributing it to Tomcat at some
point.

**Pull request merged**
