### PR TITLE
JACC Security constraints parsing for TomEE

### PR DESCRIPTION
**Pull request by ggam**
For now it just prints the results to the standard output. It's basically copied from the Geronimo `SpecSecurityBuilder`, reading the data from Tomcat parsed data, which already contains annotations.

Some missing points:
* Copyright. How exactly should I indicate on the header that the files come from Geronimo?
* Latest Geronimo version had Java EE 6 support IIRC. The `**` role was introduced on Java EE 7 and so I think it will need some modification. There are a lot of references to Servlet 2.5 that make me doubt even if this code was updated for EE 6 (I copied it from `trunk`).
* ~~This lacks runtime support for Servlets added on `ServletContainerInitializer` or `ServletContexListener` listeners~~
* ~~The Tomcat event I listen for is triggered multiple times per deployment. I'll have to figure out what's the most appropiate one.~~

As an example, this generates the following output for the Soteria `app-security-context` test:

```
-------/app-securitycontext--------
ComponentPermissions{excludedPermissions=java.security.Permissions@7e414a07 (
)
, uncheckedPermissions=java.security.Permissions@67c46023 (
 ("javax.security.jacc.WebUserDataPermission" "/protectedServlet")
 ("javax.security.jacc.WebUserDataPermission" "/:/protectedServlet")
 ("javax.security.jacc.WebResourcePermission" "/:/protectedServlet")
)
, rolePermissions={bar=java.security.Permissions@6a8c333c (
 ("javax.security.jacc.WebRoleRefPermission" "default" "bar")
 ("javax.security.jacc.WebRoleRefPermission" "" "bar")
 ("javax.security.jacc.WebRoleRefPermission" "jsp" "bar")
 ("javax.security.jacc.WebRoleRefPermission" "org.glassfish.soteria.test.ProtectedServlet" "bar")
 ("javax.security.jacc.WebRoleRefPermission" "org.glassfish.soteria.test.Servlet" "bar")
)
, kaz=java.security.Permissions@46e7562d (
 ("javax.security.jacc.WebRoleRefPermission" "jsp" "kaz")
 ("javax.security.jacc.WebRoleRefPermission" "" "kaz")
 ("javax.security.jacc.WebRoleRefPermission" "default" "kaz")
 ("javax.security.jacc.WebRoleRefPermission" "org.glassfish.soteria.test.Servlet" "kaz")
 ("javax.security.jacc.WebRoleRefPermission" "org.glassfish.soteria.test.ProtectedServlet" "kaz")
)
, foo=java.security.Permissions@32823d84 (
 ("javax.security.jacc.WebRoleRefPermission" "jsp" "foo")
 ("javax.security.jacc.WebRoleRefPermission" "default" "foo")
 ("javax.security.jacc.WebRoleRefPermission" "" "foo")
 ("javax.security.jacc.WebRoleRefPermission" "org.glassfish.soteria.test.Servlet" "foo")
 ("javax.security.jacc.WebRoleRefPermission" "org.glassfish.soteria.test.ProtectedServlet" "foo")
 ("javax.security.jacc.WebResourcePermission" "/protectedServlet")
)
}}
----------------------------------------
```

### CODE REVIEW

**Comment by arjantijms** [comment]
That’s a pretty cool start!

For Apache Licensed code there should be well established rules. IANAL, but
for ccdl (GlassFish / Mojarra) I always add the “portions copyright ...” as
instructed by the header itself. Simplest start is probably to read the
license and header to see if it says anything about this.

At the very least a simple NOTICE.md file where it’s explained which
functionality originally comes from Geronimo is always a good idea.

Slightly surprising that dynamic Servlet additions aren’t handled, as
Geronimo was EE 6 / Servlet 3.1 ad you mentioned. Doesn’t Tomcat handle
this already? So if a new Servlet is added by Tomcat, the algorithm should
be re-done I think, meaning we have to listen to that event (if any)

**Comment by ggam** [comment]
This is already working right now. Only tested the `app-securitycontext` test though.

> For Apache Licensed code there should be well established rules. IANAL, but for ccdl (GlassFish / Mojarra) I always add the “portions copyright ...” as instructed by the header itself. Simplest start is probably to read the license and header to see if it says anything about this.
>
> At the very least a simple NOTICE.md file where it’s explained which functionality originally comes from Geronimo is always a good idea.

Great, thanks. I'll take care of that before merging.

> Slightly surprising that dynamic Servlet additions aren’t handled, as Geronimo was EE 6 / Servlet 3.1 ad you mentioned. Doesn’t Tomcat handle this already? So if a new Servlet is added by Tomcat, the algorithm should be re-done I think, meaning we have to listen to that event (if any)

Latest Geronimo revision implies that it's in fact supported: https://github.com/apache/geronimo/blob/trunk/plugins/tomcat/geronimo-tomcat7-builder/src/main/java/org/apache/geronimo/tomcat/deployment/TomcatModuleBuilder.java#L667

But my code didn't support it yet ;). Now I've found the correct Tomcat event, which is fired after `ServletContextListener`s so we can take for granted that we have the latest possible configuration.

I will look at the missing pieces but I'll need your help revising the JACC algorithm for the changes introduced on Java EE 7.

**Comment by arjantijms** [comment]
Wow, very cool. Is this ready to merge now? We can address EE 7 support in a followup PR.

Btw, have you looked into adding Tomcat valve's dynamically via a service loader? It's some time ago, but I vaguely remember something like that being possible (i.e. not having to a add a jar to Tomcat).

**Comment by ggam** [comment]
Let me check the license issue first and then yes, it's ready to be merged.
Once done, I will prepare Soteria tests and fix any issues we find.

Didn't know valves can be programmatically added, I will also look at it,
thanks!

**Comment by ggam** [comment]
I just added the Apache Software Foundation copyright bits and a NOTICE file mentioning Geronimo specifically. I couldn't find the ServiceLoader valve registration you mentioned.

What I've found is that we can provide a custom AuthenticatorBase implementation (which is another valve) to override the constraint check behavior and make it use our JACC provider.

I'll provide another PR for that. In the meantime, once your merge this, could you please make another release so Soteria TomEE tests can use this module?

**Comment by arjantijms** [comment]
Hmmm, as I said it's a long time ago, but definitely remember we used that before. I'll ask Bauke, see if he remembers.

>I'll provide another PR for that. In the meantime, once your merge this, could you please make another release so Soteria TomEE tests can use this module?

Yeah, sure. Thanks for this amazing contribution!

**Pull request merged**
